name: Clean workflow runs

on:
  workflow_dispatch:
  schedule:
   - cron: "0 1 * * *"

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
